### ISSUE TITLE
Build error - Could not resolve dependencies

### ISSUE THREAD

**Issue by namednil** [allanj/dep-hybrid-tree#1]
Hi! :) Thanks for making the code available! I cloned the repository and ran `mvn clean package` and got the following error message:
```
[ERROR] Failed to execute goal on project dht: Could not resolve dependencies for project org.statnlp:dht:jar:1.0: Failed to collect dependencies at th4j-core:th4j-core_2.11:jar:0.1 -> com.typesafe.play:play-json_2.11:jar:2.3.4: Failed to read artifact descriptor for com.typesafe.play:play-json_2.11:jar:2.3.4: Could not transfer artifact com.typesafe.play:play-json_2.11:pom:2.3.4 from/to TypesafeRepo (http://repo.typesafe.com/typesafe/releases/): Connect to repo.typesafe.com:80 [repo.typesafe.com/107.21.145.22, repo.typesafe.com/34.232.236.63, repo.typesafe.com/3.225.42.70] failed: Connection refused -> [Help 1]
```
I didn't install torch but that seemed to be optional. Maybe there is a step I missed? 

The link to the compiled jar file in the readme didn't work unfortunately.

**Comment by allanj** [comment]
What JDK version do you use? 1.8 is recommended in this repo

**Comment by namednil** [comment]
Thanks for the quick reply! That was JDK 11 but I tried again with `javac 1.8.0_275` and got the same error message.

**Comment by allanj** [comment]
I  guess that might be the issue of the `th4j` package, can you try to remove these lines since you are not using torch
https://github.com/allanj/dep-hybrid-tree/blob/master/pom.xml#L57-L61

**Comment by namednil** [comment]
Thanks, that works if I remove all references to that package!
